//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class assistseniorEntities : DbContext
    {
        public assistseniorEntities()
            : base("name=assistseniorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<administrador> administrador { get; set; }
        public DbSet<cita_valoracion> cita_valoracion { get; set; }
        public DbSet<cuenta_usuario> cuenta_usuario { get; set; }
        public DbSet<enfermero> enfermero { get; set; }
        public DbSet<medico> medico { get; set; }
        public DbSet<paciente> paciente { get; set; }
        public DbSet<servicio> servicio { get; set; }
        public DbSet<turno_enfermero> turno_enfermero { get; set; }
        public DbSet<turno_medico> turno_medico { get; set; }
    }
}
