//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita_valoracion
    {
        public string idCita { get; set; }
        public string ced_paciente { get; set; }
        public string ced_medico { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
    
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
