//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta_usuario
    {
        public cuenta_usuario()
        {
            this.administrador = new HashSet<administrador>();
            this.paciente = new HashSet<paciente>();
            this.enfermero = new HashSet<enfermero>();
            this.medico = new HashSet<medico>();
        }
    
        public string email { get; set; }
        public string password { get; set; }
        public string estado { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<administrador> administrador { get; set; }
        public virtual ICollection<paciente> paciente { get; set; }
        public virtual ICollection<enfermero> enfermero { get; set; }
        public virtual ICollection<medico> medico { get; set; }
    }
}
