//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        public string idServicio { get; set; }
        public string tipoServicio { get; set; }
        public Nullable<int> duracion { get; set; }
        public string cedula_Enfermero { get; set; }
        public string cedula_Paciente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public string estado { get; set; }
    
        public virtual enfermero enfermero { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
