//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class turno_medico
    {
        public int idTurno { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan horaInicial { get; set; }
        public System.TimeSpan horaFinal { get; set; }
        public string estado { get; set; }
        public string ced_medico { get; set; }
    
        public virtual medico medico { get; set; }
    }
}
